<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tp</string>
	</array>
	<key>name</key>
	<string>DreamHost Template</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>-{-{ Yadda.index</string>
			<key>include</key>
			<string>#section</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>--var-- and --var|filter--</string>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>==include== and [[include]]</string>
			<key>include</key>
			<string>#include</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>-[-[ filters=1, this, that ]-]-</string>
			<key>include</key>
			<string>#filters</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{\{(?!/)</string>
			<key>comment</key>
			<string>{{...}}</string>
			<key>end</key>
			<string>\}\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#logic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{\{\/</string>
			<key>comment</key>
			<string>{{/...}}</string>
			<key>end</key>
			<string>\}\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#logic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>everything else is HTML</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>filters</key>
		<dict>
			<key>begin</key>
			<string>^-\[-\[</string>
			<key>end</key>
			<string>\]-\]-\s*$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#list</string>
				</dict>
			</array>
		</dict>
		<key>include</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#include-bracketed</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#include-equals</string>
				</dict>
			</array>
		</dict>
		<key>include-bracketed</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.dh-template</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.interpolated.dh-template</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.dh-template</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x) (\[\[) ([^\]]+) (\]\])</string>
		</dict>
		<key>include-equals</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.dh-template</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.interpolated.dh-template</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.dh-template</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x) (==) ([^=]+) (==)</string>
		</dict>
		<key>list</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.perl.dh-template</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.function.perl.dh-template</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x) ([^,]+?) (=?) ([^,]*?) ,?</string>
		</dict>
		<key>logic</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.comparison.perl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x) (\band\b | \bor\b | &gt;= | &lt;= | &gt; | &lt; | == | = | != | !)</string>
		</dict>
		<key>notlogic</key>
		<dict>
			<key>comment</key>
			<string>everything else between the braces that is not #logic</string>
			<key>disable</key>
			<integer>1</integer>
			<key>match</key>
			<string>(?x) (?! \b and \b ) (...) | (?! \b (or | &gt;= | &lt;= | == | != ) \b )(..) | (?! \b (&gt; | &lt; | = | !) \b )(.)</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
		<key>section</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.section.dh-template</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.filter.dh-template</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x) ^ -{-{ \s* (\S+) \( ?(.*) \)? \s* $</string>
		</dict>
		<key>variable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable-filtered</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-subtitution</string>
				</dict>
			</array>
		</dict>
		<key>variable-filtered</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.perl.dh-template</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.predefined.perl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.function.perl.dh-template</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.perl.dh-template</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x) (--) ([^\|-]+) \| ([^-]+) (--)</string>
		</dict>
		<key>variable-subtitution</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.perl.dh-template</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.predefined.perl.dh-template</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.perl.dh-template</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x) (--) ([^-]+) (--)</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.dh-template</string>
	<key>uuid</key>
	<string>71b8d29d-07b2-4fc3-970c-d3ab59286976</string>
</dict>
</plist>
